#pragma config(Sensor, S1,     leftTouch,      sensorEV3_Touch)
#pragma config(Sensor, S2,     gyroSensor,     sensorEV3_Gyro, modeEV3Gyro_RateAndAngle)
#pragma config(Sensor, S3,     rightTouch,     sensorEV3_Touch)
#pragma config(Sensor, S4,     sonarSensor,    sensorEV3_Ultrasonic)
#pragma config(Motor,  motorA,          armMotor,      tmotorEV3_Large, openLoop, encoder)
#pragma config(Motor,  motorB,          leftMotor,     tmotorEV3_Large, openLoop, driveLeft, encoder)
#pragma config(Motor,  motorC,          rightMotor,    tmotorEV3_Large, openLoop, driveRight, encoder)
#pragma config(Motor,  motorD,           ,             tmotorEV3_Large, openLoop, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

void forward(int a);
void reverse(int a);
void right_turn(int b);
void left_turn(int b);
void leave_package();
void touch_wall();
void go_stop_before_wall();

task main()
{

	touch_wall();
	sleep(500);
	reverse(15);
	sleep(500);
	right_turn(180);
	sleep(500);
	go_stop_before_wall();
	sleep(500);
	right_turn(90);
	sleep(500);
	forward(250);
	sleep(500);

//Leave package and reverse function
	leave_package();
	sleep(500);

	right_turn(180);
	sleep(500);
	forward(245);
	sleep(500);
	left_turn(90);
	sleep(500);

		do{
		setMotorSync(leftMotor, rightMotor, 0, 30);
	}
	while ((getTouchValue(rightTouch)==0)||(getTouchValue(leftTouch)==0));
	reverse(50);
	sleep(500);

}

void forward(int a)
{
	float target_dist = (a / (3*PI)) * 360;
		resetMotorEncoder(leftMotor);
	resetMotorEncoder(rightMotor);

	setMotorSyncEncoder(motorB, motorC, 0, target_dist, 30);

	waitUntilMotorStop(motorB);
	waitUntilMotorStop(motorC);
}

void reverse(int a)
{
	float target_dist = (a / (3*PI)) * 360;
		resetMotorEncoder(leftMotor);
	resetMotorEncoder(rightMotor);

	setMotorSyncEncoder(motorB, motorC, 0, target_dist, -20);

	waitUntilMotorStop(motorB);
	waitUntilMotorStop(motorC);
}

void right_turn(int b)
{
	float circ_Axel = 11.7;
	float circ_Wheel = 3.0;
	float v = b;
	float target_deg = (circ_Axel/circ_Wheel) * v;

	resetMotorEncoder(leftMotor);
	resetMotorEncoder(rightMotor);
	sleep(1000);
	setMotorSyncEncoder(motorB, motorC, 100, target_deg, 10);

	waitUntilMotorStop(motorB);
	waitUntilMotorStop(motorC);
}

void left_turn(int b)
{
	float circ_Axel = 11.7;
	float circ_Wheel = 3.0;
	float v = b;

	float target_deg = (circ_Axel/circ_Wheel) * v;

	resetMotorEncoder(leftMotor);
	resetMotorEncoder(rightMotor);
	sleep(1000);
	setMotorSyncEncoder(motorB, motorC, -100, target_deg, 10);

	waitUntilMotorStop(motorB);
	waitUntilMotorStop(motorC);
}

void leave_package()
{
		resetMotorEncoder(armMotor);
	do {
		setMotorTarget(armMotor, 1440, 50);
	}
	while (getMotorEncoder(armMotor) < getMotorTarget(armMotor));

	setMotorSync(leftMotor,rightMotor,0, -10);
	sleep(2000);
	setMotorSpeed(leftMotor, 0);
	setMotorSpeed(rightMotor, 0);
	sleep(500);
}

void touch_wall()
{
	do{
		setMotorSync(leftMotor, rightMotor, 0, 30);
	}
	while ((getTouchValue(rightTouch)==0)||(getTouchValue(leftTouch)==0));
}

void go_stop_before_wall()
{
do{
		setMotorSync(leftMotor,rightMotor, 0, 50);//Motors run forward in sync

	}while (getUSDistance(sonarSensor) > 15);
	setMotorSpeed(leftMotor, 0);
	setMotorSpeed(rightMotor, 0);
}
