#pragma config(StandardModel, "EV3_REMBOT")
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

 task main()
 {

 //Drive towards the wall
	while (getUSDistance(sonarSensor) > 15)
	{
		setMotorSpeed(leftMotor, 50);
		setMotorSpeed(rightMotor, 50);
	}
	setMotorSpeed(leftMotor, 0);
	setMotorSpeed(rightMotor, 0);
	sleep(1000);


	//Turn to the right
resetGyro(S2);
repeatUntil(getGyroDegrees(S2) > 90)
{
	setMotorSpeed(motorC, -20);
	setMotorSpeed(motorB, 10);
}
setMotorSpeed(motorC, 0);
setMotorSpeed(motorB, 0);

//Drive to drop off point

moveMotorTarget(motorB, 5400, 90);
moveMotorTarget(motorC, 5400, 90);
waitUntilMotorStop(motorB);
waitUntilMotorStop(motorC);

//Leave package

//Reverse motor 17 cm

moveMotorTarget(motorB, -360, 50);
moveMotorTarget(motorC, -360, 50);
waitUntilMotorStop(motorB);
waitUntilMotorStop(motorC);


//Turn 180 degrees

resetGyro(S2);
repeatUntil(getGyroDegrees(S2) > 175)
{
	setMotorSpeed(motorC, -25);
	setMotorSpeed(motorB, 25);
}
setMotorSpeed(motorB, 0);
setMotorSpeed(motorC, 0);

//Drive back

moveMotorTarget(motorB, 5040, 90);
moveMotorTarget(motorC, 5040, 90);
waitUntilMotorStop(motorB);
waitUntilMotorStop(motorC);

//Turn towards start point

resetGyro(S2);
repeatUntil(getGyroDegrees(S2) == -85)
{
	setMotorSpeed(motorC, 25);
	setMotorSpeed(motorB, -25);
}
setMotorSpeed(motorB, 0);
setMotorSpeed(motorC, 0);

//Drive to startpoint

moveMotorTarget(motorB, 1080, 75);
moveMotorTarget(motorC, 1080, 75);
waitUntilMotorStop(motorB);
waitUntilMotorStop(motorC);

}
