#pragma config(Sensor, S1,     touchSensor,    sensorEV3_Touch)
#pragma config(Sensor, S2,     gyroSensor,     sensorEV3_Gyro, modeEV3Gyro_RateAndAngle)
#pragma config(Sensor, S3,     colorSensor,    sensorEV3_Color, modeEV3Color_Color)
#pragma config(Sensor, S4,     sonarSensor,    sensorEV3_Ultrasonic)
#pragma config(Motor,  motorA,          armMotor,      tmotorEV3_Medium, PIDControl, encoder)
#pragma config(Motor,  motorB,          leftMotor,     tmotorEV3_Large, PIDControl, driveLeft, encoder)
#pragma config(Motor,  motorC,          rightMotor,    tmotorEV3_Large, PIDControl, driveRight, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	sensorReset(S2);
	sensorReset(S4);
	//Drive to wall and stop 15 cm from.
	do{
		setMotorSync(leftMotor,rightMotor, 0, 25);//Motors run forward in sync

	}while (getUSDistance(sonarSensor) > 15);

	setMotorSpeed(leftMotor, 0);
	setMotorSpeed(rightMotor, 0);
	sleep(1000);


	//Turn 90 degrees to the right
resetGyro(S2);
do{
	setMotorSync(leftMotor, rightMotor, 100, 20);
	}while (getGyroDegrees(S2) < 90);

	setMotorSpeed(motorC, 0);
	setMotorSpeed(motorB, 0);
	sleep(1000);


	//Drive forward
	resetMotorEncoder(leftMotor);
	resetMotorEncoder(rightMotor);
	setMotorSyncEncoder(leftMotor, rightMotor, 0, 9555, 50);
	waitUntilMotorStop(leftMotor);
	waitUntilMotorStop(rightMotor);
	sleep(1000);

	//Leave package and reverse function
	resetMotorEncoder(armMotor);
	setMotorTarget(armMotor, 1440, 50);
	repeatUntil(getMotorEncoder(armMotor) == getMotorTarget(armMotor))

	setMotorSync(leftMotor,rightMotor,0, -10);
	sleep(2000);
	setMotorSpeed(leftMotor, 0);
	setMotorSpeed(rightMotor, 0);
	sleep(1500);


	//Turn 180 degrees

	resetGyro(S2);
	repeatUntil(getGyroDegrees(S2) > 180)
	{
		setMotorSpeed(motorC, -10);
		setMotorSpeed(motorB, 10);
	}
	setMotorSpeed(motorB, 0);
	setMotorSpeed(motorC, 0);
	sleep(1000);

	//Drive back
	int c;
	c = ( 250*120/PI); // Replace in  _*120/PI with distance in cm.

	resetMotorEncoder(leftMotor);
	resetMotorEncoder(rightMotor);
	setMotorSyncEncoder(leftMotor, rightMotor, 0, c, 50);
	waitUntilMotorStop(leftMotor);
	waitUntilMotorStop(rightMotor);
	sleep(1000);

	//Turn towards start point

	resetGyro(S2);
	repeatUntil(getGyroDegrees(S2) < -90)
	{
		setMotorSpeed(motorC, 10);
		setMotorSpeed(motorB, -10);
	}
	setMotorSpeed(motorB, 0);
	setMotorSpeed(motorC, 0);
	sleep(1000);

	//Drive to startpoint
	int f;
	f = ( 35*120/PI); // Replace 25 in ( 25*120/PI)with distance in cm.

	resetMotorEncoder(leftMotor);
	resetMotorEncoder(rightMotor);
	setMotorSyncEncoder(leftMotor, rightMotor, 0, f, 50);
	waitUntilMotorStop(leftMotor);
	waitUntilMotorStop(rightMotor);
	sleep(1000);
}
